require("./app/js/offlineRuntimeInstall");
require("materialize-loader!./app/materialize.config.js");
// require("./node_modules/material-icons/css/material-icons.css");
// require("./node_modules/material-icons/css/material-icons.css");
require("leaflet");
require("./node_modules/leaflet.markercluster/dist/leaflet.markercluster");
require("./app/js/master");
require("./app/js/menu");
require("./app/js/propiedad");
// require("./node_modules/materialize-css/sass/materialize.scss");
// require("./app/css/variables.scss");
require("./node_modules/material-design-icons/iconfont/material-icons.css");
require("./node_modules/leaflet/dist/leaflet.css");
require("./node_modules/leaflet.markercluster/dist/MarkerCluster.css");
// require("./node_modules/leaflet.markercluster/dist/MarkerCluster.Default.css");
require("./app/css/leaflet.css");
require("./app/css/master.css");
